### ISSUE TITLE
Change Date.now to performance.now()?

### ISSUE THREAD

**Issue by joshribakoff** [dai-shi/will-this-react-global-state-work-in-concurrent-mode#23]
https://www.w3.org/TR/hr-time-2/#dom-domhighrestimestamp

> these definitions of time are subject to both clock skew and adjustment of the system clock. The value of time may not always be monotonically increasing and subsequent values may either decrease or remain the same.

> For example, the following script may record a positive number, negative number, or zero for computed duration:

> EXAMPLE 1
>var mark_start = Date.now();
> doTask(); // Some task
> var duration = Date.now() - mark_start;
> For certain tasks this definition of time may not be sufficient as it does not allow for sub-millisecond resolution and is subject to system clock skew.

I can volunteer to make a PR if you agree

**Comment by dai-shi** [comment]
I agree!
