### ISSUE TITLE
zustand update

### ISSUE THREAD

**Issue by alievrenkut** [dai-shi/will-this-react-global-state-work-in-concurrent-mode#31]
Hi, 

I saw your commits to zustand code base. Is zustand latest version different from your last test?
Do you think in the future zustand will support every case? Or some cases will be impossible?

Thank you for your attention to react concurrent mode issues.

**Comment by dai-shi** [comment]
Current test is on v3.2.0 and the latest version is v3.3.1. I suppose the result is the same.

With the future version (PR here https://github.com/pmndrs/zustand/pull/160 ), I would expect it's safe in CM.

Note that the goal is not to make all green. Especially, check 7 is for React state only. Theoretically, it's not possible for module state like zustand, redux and many others.
