### ISSUE TITLE
Need Help, why my MR faield

### ISSUE THREAD

**Issue by fantasticsoul** [dai-shi/will-this-react-global-state-work-in-concurrent-mode#34]
I just forked this project and add [concent](https://github.com/concentjs/concent)
https://github.com/concentjs/will-this-react-global-state-work-in-concurrent-mode

Here is my MR:
https://github.com/dai-shi/will-this-react-global-state-work-in-concurrent-mode/pull/33

and this is the error log from travis-ci:
https://travis-ci.com/github/dai-shi/will-this-react-global-state-work-in-concurrent-mode/jobs/497638741

**Comment by dai-shi** [comment]
https://github.com/dai-shi/will-this-react-global-state-work-in-concurrent-mode/pull/33#issuecomment-821151278
