### ISSUE TITLE
Library: react-scoped-model

### ISSUE THREAD

**Issue by LXSMNSYC** [dai-shi/will-this-react-global-state-work-in-concurrent-mode#4]
Good day!

I saw this repository while exploring Github, and I stumbled upon this test repo.
Strange, I have never heard of "tearing" before and I am curious to know what is it, and then I saw your screencast image on the repo's README.

Having a state management library being used in production, I would also like to add my library, [react-scoped-model](https://github.com/LXSMNSYC/react-scoped-model), in the test suite.

My team are also planning to migrate our app (which uses the said library) to concurrent mode when the feature is released ASAP, which gave me concerns about the state of my library.

**Comment by dai-shi** [comment]
If it is a reducer-based library, it should be easy.
Please fork this repo and try adding yours on your fork.
You can ask here if you have difficulties in understanding how it's working.

Important note: This "tearing" is a hypothetical issue that might be a problem in certain apps. In my understanding, it will not be a problem for most apps. So, in general, you want to try your app in CM and see what are problems at first.

**Comment by LXSMNSYC** [comment]
Thanks for the quick reply!

Unfortunately, our app is written in SSR (using Next, specifically) and we are looking forward on the support for CM on Next, which is why we are now adapting to its patterns as published in the ReactJS website.
